language: android
dist : trusty

before_install:
  - yes | sdkmanager "platforms;android-28"

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-$ANDROID_TARGET
    - $ANDROID_TARGET
    - sys-img-armeabi-v7a-$ANDROID_TARGET
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

env:
  matrix:
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a

before_script:
  - echo no | android create avd --force -n test -s "1080x1920" -t $ANDROID_TARGET --abi $ANDROID_ABI -c 200M
  - emulator -avd test -no-skin -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - sleep 200
  - adb devices
  - adb shell appops set de.freakyblue.gpsdemo 58 allow


