language: android
dist : trusty

before_install:
  - yes | sdkmanager "platforms;android-28"

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-$ANDROID_TARGET
    - $ANDROID_TARGET
    - sys-img-armeabi-v7a-$ANDROID_TARGET
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

env:
  matrix:
    - ANDROID_TARGET=android-24  ANDROID_ABI=armeabi-v7a

before_script:
  - android list targets
  - echo no | android create avd --force -n test -s "1080x1920" -t "sys-img-x86-android-24" -c 200M
  - emulator -avd test -no-skin -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - adb --version
  - adb shell pm list permissions
  - sleep 10
  - adb devices
  - ./gradlew build installDebug
  - adb shell  'pm list packages -f'
  - adb shell appops set de.freakyblue.gpsdemo android:mock_location allow
  - adb shell appops set de.freakyblue.gpsdemo 58 allow
  - adb shell appops set de.freakyblue.gpsdemo permission:android.permission.ACCESS_MOCK_LOCATION allow
  - adb shell appops set de.freakyblue.gpsdemo android.permission.ACCESS_MOCK_LOCATION allow
  - adb shell appops set de.freakyblue.gpsdemo ACCESS_MOCK_LOCATION allow
  - adb shell appops set 0 de.freakyblue.gpsdemo 58 allow

  - adb shell appops get de.freakyblue.gpsdemo 58


#  - adb shell appops set de.freakyblue.gpsdemo MOCK_LOCATION allow
#  - adb shell appops set de.freakyblue.gpsdemo "MOCK_LOCATION" allow
#  - adb shell appops set de.freakyblue.gpsdemo OP_MOCK_LOCATION allow
#  - adb shell appops set de.freakyblue.gpsdemo android:mock_location allow
#  - adb shell appops set de.freakyblue.gpsdemo "android:mock_location" allow
# - adb shell appops set de.freakyblue.gpsdemo OPSTR_MOCK_LOCATION allow


