language: android
dist : trusty

before_install:
  - yes | sdkmanager "platforms;android-28"

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-$ANDROID_TARGET
    - $ANDROID_TARGET
    - sys-img-armeabi-v7a-$ANDROID_TARGET
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

env:
  matrix:
    - ANDROID_TARGET=android-24  ANDROID_ABI=armeabi-v7a

before_script:
  - android list targets
